version: '2'
services:
    redis:
      image: redis:latest
      ports:
        - 6379:6379
    web:
      restart: always
      build: .
      command: daphne -b 0.0.0.0 -p 8000 cottagesite.asgi:application
      #command: python manage.py runserver 0.0.0.0:8000
      ports:
        - 8000:8000 
      volumes:
        - .:/usr/src/app
      links:
        - redis
    worker:
      build: .
      command: python manage.py runworker
      volumes:
        - .:/usr/src/app
