version: '2'
services:
    redis:
      image: redis:latest
    web:
      build: .
      command: daphne -b 0.0.0.0 -p 8000 cottagesite.asgi:application
      ports:
        - 8000:8000 
      volumes:
        - .:/usr/src/app
      links:
        - redis
    worker:
      build: .
      command: python manage.py runworker
      volumes:
        - .:/usr/src/app
